name: zikzak_html_to_markdown
description: HTML to Markdown converter
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  zikzak_inappwebview: ^1.2.6
  html2md: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
